name: solana-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - anyio=4.3.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - dataclasses-json=0.6.4
  - exceptiongroup=1.2.0
  - frozenlist=1.4.0
  - greenlet=3.0.1
  - idna=3.6
  - iniconfig=2.0.0
  - intel-openmp=2023.1.0
  - jsonpatch=1.33
  - jsonpointer=2.0
  - langchain=0.1.9
  - langchain-community=0.0.22
  - langchain-core=0.1.26
  - langsmith=0.1.5
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - marshmallow=3.20.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.0.13
  - packaging=23.2
  - pip=23.3.1
  - pluggy=1.4.0
  - pysocks=1.7.1
  - pytest=8.0.1
  - pytest-subtests=0.11.0
  - python=3.11.7
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sniffio=1.3.0
  - sqlalchemy=2.0.25
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tenacity=8.2.3
  - tk=8.6.12
  - tomli=2.0.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_inspect=0.9.0
  - tzdata=2023d
  - urllib3=2.2.1
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - pip:
      - annotated-types==0.6.0
      - argparse==1.4.0
      - cachetools==4.2.4
      - click==8.1.7
      - construct==2.10.68
      - construct-typing==0.5.6
      - distro==1.9.0
      - fastapi==0.109.2
      - h11==0.14.0
      - hiredis==2.3.2
      - httpcore==0.16.3
      - httpx==0.23.3
      - jsonalias==0.1.1
      - langchain-experimental==0.0.52
      - langchain-openai==0.0.7
      - mypy==1.8.0
      - nest-asyncio==1.6.0
      - openai==1.12.0
      - pydantic==2.6.1
      - pydantic-core==2.16.2
      - redis==5.0.1
      - regex==2023.12.25
      - rfc3986==1.5.0
      - solana==0.32.0
      - solders==0.20.0
      - starlette==0.36.3
      - tavily-python==0.3.1
      - tiktoken==0.5.2
      - tqdm==4.66.2
      - types-cachetools==4.2.10
      - uvicorn==0.27.1
      - websockets==11.0.3
